---

- name: Install CentOS Epel Repository
  include_role:
    name: geerlingguy.repo-epel
  when: ansible_distribution == 'CentOS'

- name: Install Git
  include_role:
    name: geerlingguy.git

- name: Install Python 2 & 3
  package:
    state: present
    name:
      - python
      - python3

- name: Install Python 2 Pip
  include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python-pip

- name: Install Python 3 Pip
  include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip

 # needed to install ansible via pip on centos7
- name: Install Python 2 & 3 Cryptography
  package:
    state: present
    name:
      - python2-cryptography
      - python36-cryptography
  when: ansible_distribution == 'CentOS'

- name: Install Ansible Python 3 packages
  pip:
    executable: pip3
    state: present
    name:
      - "ansible=={{ ifb_ansible_version }}"
      - ansible-lint
      - molecule

 # needed  for the The ipv4 ansible filter
- name: Install Python 2 & 3 netaddr
  package:
    state: present
    name:
      - python-netaddr
      - python36-netaddr
  when: ansible_distribution == 'CentOS'



# clean mode
- name: Uninstall OS Package
  package:
    state: absent
    name:
      - ansible
      - ansible-lint

# warning : it look like ansible unsinstall from python 2 pip does not work well, as after it there are still a /usr/bin/ansible linked to /usr/lib/python2.7/site-packages/ansible/constants.py
- name: Uninstall Python 2 package
  pip:
    executable: pip
    state: absent
    name:
      - ansible
      - ansible-lint
